name: CI

on: 
  [push, pull_request] 
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare Build
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install ninja
      env:
        CC: gcc
    - name: Build

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      - name: Zip
        uses: papeloto/action-zip@v1

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare Build
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: brew install gcc
    - run: pip install ninja
      env:
        CC: gcc
    - name: Build

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      - name: Zip
        uses: papeloto/action-zip@v1

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare Build
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install ninja
    - uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: x64
    - name: Build
  
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      - name: Zip
        uses: papeloto/action-zip@v1
